---
# tasks file for upgrade_system
  
- name: Upgrade all packages, excluding kernel & foo related packages
  yum:
    name: '*'
    state: latest
    exclude: kernel*,foo*
  notify: Reboot host
  when: ansible_os_family == "RedHat"

- name: Remove old kernels from the OS keeping only the last most recent two
  command: /usr/bin/package-cleanup --oldkernels --count=2 -y
  